Repository Dymension-League/frontend, pull requests merged in 2024-08, with the labels that each got.

#21 Frontend/update create page
  .env.sample
  package-lock.json
  package.json
  src/App.js
  src/App.test.tsx
  src/App.tsx
  src/artifacts/contracts/CosmoShips.json
  src/artifacts/contracts/GameLeague.json
  src/artifacts/contracts/contracts.ts
  src/assets/space-ships/spaceships.js
  src/components/footer/NewFooter.jsx
  src/components/header/HeaderLeague.jsx
  src/components/header/NetworkButton.tsx
  src/components/header/WalletButton.tsx
  src/components/layouts/home-5b/CreateTeam/CreateTeam.jsx
  src/components/layouts/home-5b/CreateTeam/CreateTeamPage.tsx
  src/components/layouts/home-5b/CreateTeam/LiveAuction.jsx
  src/components/layouts/home-5b/MintShip/MintShip.tsx
  src/components/layouts/home-5b/MintShip/SliderShips.jsx
  src/components/layouts/home-5b/styles/Home05b.css
  src/components/logoIcon/LogoIcon.tsx
  src/components/slider/Slider.jsx
  src/components/slider/SliderStyle2.jsx
  src/config/index.ts
  src/global.d.ts
  src/index.js
  src/index.tsx
  src/pages/CreateTeam/CreateTeamPage.jsx
  src/pages/HeaderMenu/headerMenus.js
  src/pages/Home/HomePage.jsx
  src/pages/Home05b.jsx
  src/pages/MintShip/MintShipPage.jsx
  src/pages/index.js
  src/services/ImageCacheService.js
  src/services/contracts/cosmoships.service.ts
  src/services/contracts/gameleague.service.ts
  yarn.lock
Labels: FE, Smart Contracts, Beta Testnet

#26 Create Team Update
  package.json
  src/components/layouts/home-5b/CreateTeam/CreateTeam.jsx
  src/components/layouts/home-5b/CreateTeam/CreateTeamPage.tsx
  src/components/layouts/home-5b/CreateTeam/NewTeam.jsx
  src/components/layouts/home-5b/MintShip/SliderShips.jsx
  src/config/index.ts
  src/pages/CreateTeam/CreateTeamPage.jsx
  src/pages/index.js
  src/services/ImageCacheService.js
  src/services/contracts/cosmoships.service.ts
  src/services/ipfsUtils.ts
Labels: FE, Beta Testnet

#34 Fix: fix bet page, and simplify types (use only Ship)
  .gitignore
  src/components/layouts/home-5b/Bet/PlaceBetPage.tsx
  src/components/layouts/home-5b/CreateTeam/CreateTeamPage.tsx
  src/components/layouts/home-5b/CreateTeam/NewTeam.tsx
  src/components/layouts/home-5b/CreateTeam/ShipCard.tsx
  src/components/layouts/home-5b/EnrollTeam/EnrollTeam.tsx
  src/components/layouts/home-5b/EnrollTeam/TeamCard.tsx
  src/components/layouts/home-5b/styles/Home05b.css
  src/services/contracts/cosmoships.service.ts
Labels: FE, Beta Testnet, services

#35 Fix/header
  .env.sample
  src/components/header/Header.jsx
  src/components/header/Header.tsx
  src/components/header/HeaderLeague.jsx
  src/components/header/HeaderMenu/headerMenus.ts
  src/components/header/HeaderStyle2.jsx
  src/components/header/navbar/ProdNav.tsx
  src/components/header/navbar/TestNav.tsx
  src/pages/Bet/BetPage.tsx
  src/pages/CreateTeam/CreateTeamPage.jsx
  src/pages/EnrollTeam/EnrollTeamPage.jsx
  src/pages/Home/HomePage.jsx
  src/pages/Home04.jsx
  src/pages/Home05.jsx
  src/pages/Home05b.jsx
  src/pages/Home06.jsx
  src/pages/Home07.jsx
  src/pages/Home08.jsx
  src/pages/MintShip/MintShipPage.jsx
  src/pages/MintShipsPage.jsx
  src/pages/NotFound.tsx
  src/pages/index.js
  src/pages/index.tsx
Labels: FE, Beta Testnet

#39 FE/Landing Page
  src/components/footer/NewFooter.jsx
  src/components/layouts/home-5b/MintShip/SliderShips.jsx
  src/pages/Home/HomePage.jsx
  src/pages/SpaceshipsAuctions.jsx
Labels: enhancement, FE, Beta Testnet

#45 simplify minting section
  src/components/layouts/home-5b/MintShip/MintSection.tsx
  src/components/layouts/home-5b/MintShip/MintShip.tsx
  src/components/layouts/home-5b/styles/Home05b.css
Labels: enhancement, FE, Beta Testnet
